CREATE TABLE JENKINS_TEST_REPORT (
PROJECT_NAME VARCHAR(50),
CXP_NUMBER VARCHAR(50),
TESTS_PASSED  INT,
TESTS_FAILED INT,
TESTS_SKIPPED INT,
SUCCESS_RATE DECIMAL(4,2),
FAILURE_RATE DECIMAL(4,2),
BUILD_NUMBER INT,
BUILD_TIME_STAMP BIGINT ,
BUILD_RELEASE_TYPE VARCHAR(20),
PRIMARY KEY (PROJECT_NAME, CXP_NUMBER, BUILD_RELEASE_TYPE, BUILD_NUMBER)
);

CREATE INDEX CXP_NUMBER_INDEX ON JENKINS_TEST_REPORT (CXP_NUMBER);
CREATE INDEX PROJECT_NAME_INDEX ON JENKINS_TEST_REPORT (PROJECT_NAME);
CREATE INDEX FAILURE_RATE_INDEX ON JENKINS_TEST_REPORT (FAILURE_RATE);
CREATE INDEX SUCCESS_RATE_INDEX ON JENKINS_TEST_REPORT (SUCCESS_RATE);


CREATE TABLE PROJECT_LAST_BUILD_NUMBER (
PROJECT_NAME VARCHAR(50),
BUILD_RELEASE_TYPE VARCHAR(20),
LAST_BUILD_NUMBER INT,
PRIMARY KEY (PROJECT_NAME, BUILD_RELEASE_TYPE));

CREATE INDEX PROJECT_NAME_INDEX_LAST_BUILD_NUMBER_TABLE ON PROJECT_LAST_BUILD_NUMBER (PROJECT_NAME);
